### ISSUE TITLE
Add a `deploy` command

### ISSUE THREAD

**Issue by sgrif** [rust-lang/crates-io-ops-bot#3]
One of the most common things we'll want to do with the bot is deploy new code. This command should take a sha as a single argument.

- [x] This command should in some way mirror the effects of cloning the GitHub repository, and running `git push heroku master`. One option is to actually just subshell out to git, but there may be APIs we can use to make this easier
- [ ] The remote we pull from should be configured by an environment variable
- [ ] The remote we push to can either be retrieved through the heroku CLI, or should be set by an environment variable
- [ ] This command should *not* force push by default, but needs to provide some way to allow one
  - This could be done by some interactive confirmation, or by having the command optionally end with `force` or something, e.g. `deploy sha force`
- [x] This command should not pipe output from any of these commands, as the build output is too verbose and can be seen elsewhere
- [x] The command should give some indication that the build has successfully started (ideally mentioning both the previous and new shas), or output errors if any occurred (not errors from the build itself, but errors starting the build)
- [ ] Optional nice to have: Provide a link to the build output.
  - Their API provides a URL for this. See https://devcenter.heroku.com/articles/platform-api-reference#build

**Comment by nellshamrell** [comment]
This should be implementable entirely through the Heroku Platform API.

Specifically using these resources
* [Build Create](https://devcenter.heroku.com/articles/platform-api-reference#build-create)
* Capture the [Slug](https://devcenter.heroku.com/articles/platform-api-reference#slug) ID from the [Build Info](https://devcenter.heroku.com/articles/platform-api-reference#build-info)
* Create a release using [Release Create](https://devcenter.heroku.com/articles/platform-api-reference#release)

Workflow I'm thinking of:
* User runs ~deploy command, passing GitHub source URL (we can also configure this through an environmental variable) and the commit id to deploy)
* Bot creates a build (buildpack will either by specified as a constant or can be an environmental variable as well), then creates a release
* Bot returns build output and release output to Discord chat

**Comment by nellshamrell** [comment]
This was implemented in #25
