### ISSUE TITLE
Double deploy happening

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/crates-io-ops-bot#44]
It seems like Heroku deploys the build on its own after finishing to build, and *then* the bot tries to deploy the change:

![2020-06-05--15-06-38](https://user-images.githubusercontent.com/2299951/83879630-3eb3c080-a73e-11ea-9b2a-9637e2a348c3.png)

We should either avoid doing our own deploy, or configure Heroku to avoid deploying on its own.

**Comment by nellshamrell** [comment]
Fixed in #47
