### ISSUE TITLE
Add a `config` command

### ISSUE THREAD

**Issue by sgrif** [rust-lang/crates-io-ops-bot#5]
This command should allow both reading and writing config vars. Config vars can be read via `heroku config:get VAR`, and written via `heroku config:set VAR_NAME`. Alternatively, they could be handled through the API https://devcenter.heroku.com/articles/platform-api-reference#config-vars.

- [ ] The command should pipe the output of any processes it subshells out to.
- [x] The variables which can be handled through the bot should be a configurable allowlist. Either command should error if given a config var that is not in the allowlist.

**Comment by nellshamrell** [comment]
I'm implemented most of this in #22 - could you tell me more about "The command should pipe the output of any processes it subshells out to" - could you give me an idea of what you would want to see there?

**Comment by nellshamrell** [comment]
I don't think it needs to subshell into anything, so I'm going to go ahead and close this issue.
