### ISSUE TITLE
Add a `rollback` command

### ISSUE THREAD

**Issue by sgrif** [rust-lang/crates-io-ops-bot#6]
This command should mirror the behavior of `heroku releases:rollback`, which optionally takes a single release name as an argument.

- [ ] The command should pipe the output of any processes it subshells out to
- [ ] Optional nice to have: Some form of confirm dialog
- [ ] Optional nice to have: Error if the command is run too frequently -- if we want to go back 3 releases we would specify it by name.

**Comment by nellshamrell** [comment]
Implemented with #23 (without the optional nice to haves - but I'm happy to come back to those in the future)
